apps/cryptics/urls.py
from django.urls import path
from . import views

app_name = "cryptics"

urlpatterns = [
	path("", views.index, name="index"),
	path("about", views.about, name="about"),
	path("contest/<int:contest_id>", views.show_contest, name="show_contest"),
	path("contest/<int:contest_id>-<word>", views.show_contest_full, name="show_contest_full"),
	path("contest/search", views.contest_search_json, name="contest_search"),
	path("submission/<int:submission_id>/like", views.add_like, name="add_like"),
	path("submission/<int:submission_id>/dislike", views.remove_like, name="remove_like"),
	path("all_users", views.all_users, name="all_users"),
	path("user/<int:user_id>", views.show_user, name="show_user"),
	path(
		"submission/<int:submission_id>/delete",
		views.delete_submission,
		name="delete_submission"
	),
	path("archives", views.all_closed_contests, name="all_closed_contests"),
]

cryptic_contest/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("apps.cryptics.urls")),
    path("accounts/", include("allauth.urls")),
]

apps/cryptics/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.template.defaultfilters import pluralize

from .models import Contest, Submission


class ContestForm(forms.ModelForm):

    word = forms.CharField(widget=forms.TextInput(attrs={"id": "new_contest_word"}))

    class Meta:
        model = Contest
        fields = ["word", "started_by"]

    template_name = "cryptics/contest_form.html"
    # Note that this template to hard-coded to only display the "word" field—if I add additional fields to this form
    # in the future (unlikely, but one never knows), the template will need to be rewritten.  Also note that
    # started_by is a field on this form for validation/model creation purposes, but it isn't included on the form
    # itself; the view will need to manually add that (based on request.user) to the POST data before instantiating
    # the form.

    def clean_started_by(self):
        """ Make sure a user only has a single open contest at a time """
        started_by = self.cleaned_data["started_by"]
        if started_by.contests_started.filter(status=Contest.SUBMISSIONS).exists():
            raise ValidationError("Each user can only have one active contest at a time.", code="already_open_contest")
        return started_by

    def save(self, commit=True):
        obj = super().save(commit=False)  # This includes a check that there were no errors
        if commit:
            return Contest.objects.add(**self.cleaned_data)
        else:
            return obj


class SubmissionForm(forms.ModelForm):
    clue = forms.CharField(
        widget=forms.TextInput(attrs={"size": 60, "id": "new_submission"}),
        error_messages={"required": "Clue is required."}
    )
    explanation = forms.CharField(
        widget=forms.Textarea(attrs={"rows": 4, "cols": 40}), error_messages={"required": "Explanation is required."}
    )

    class Meta:
        model = Submission
        fields = ["clue", "explanation", "contest", "submitted_by"]

    template_name = "cryptics/submission_form.html"

    def clean_submitted_by(self):
        """ Make sure a user likes a certain number of other people's submissions for each clue they submit

        I do this to encourage more participation.  At the moment, it's very loose—you have to give at least one like
        for every two clues you submit.
        """
        submitter = self.cleaned_data["submitted_by"]
        likes_needed_to_give = submitter.submissions.count() // 2 - submitter.clues_liked.count()

        if likes_needed_to_give > 0:
            raise ValidationError(
                f"Please like at least {likes_needed_to_give} more clue{pluralize(likes_needed_to_give)}"
            )

        return submitter

    def clean_contest(self):
        contest = self.cleaned_data["contest"]
        contest.check_if_too_old()
        if not contest.is_submissions:
            raise ValidationError("Sorry, this contest has closed.")
        return contest

    def save(self, commit=True):
        obj = super().save(commit=False)
        if commit:
            return Submission.objects.add(**self.cleaned_data)
        else:
            return obj


class ContestSearchForm(forms.Form):
    """ Form for the GET params of the contest search field

    This is overkill now, but can be extended if we want to accept more complicated search/filtering (such as
    different sort orders or pagination)
    """
    search = forms.CharField()

apps/cryptics/views.py
from http import HTTPStatus

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.urls import reverse
from django.shortcuts import render, redirect, get_object_or_404

from .forms import ContestForm, ContestSearchForm, SubmissionForm
from .models import User, Contest, Submission


def index(request):
	""" Show the main page """
	if request.method == "POST":
		if request.user.is_anonymous:
			return redirect("account_login")

		form = ContestForm({"word": request.POST.get("word"), "started_by": request.user})

		if form.is_valid():
			form.save()
			return redirect("cryptics:index")
	else:
		form = ContestForm()

	context = {"form": form}

	context["open_contests"] = Contest.objects.filter(status=Contest.SUBMISSIONS).order_by("created_at")

	context["voting_contests"] = Contest.objects.filter(status=Contest.VOTING).order_by("created_at")

	context["past_contests"] = Contest.objects.ended_recently()
	context["current_champ"] = User.objects.sort_users()[0]
	context["recent_clues"] = Submission.objects.all().order_by("-created_at")[:3]

	return render(request, "cryptics/index.html", context)


def about(request):
	""" Show the about page """
	return render(request, "cryptics/about.html")


def show_contest(request, contest_id):
	""" Redirect show_contest requests with just the ID to ID and contest slug URL """
	contest = get_object_or_404(Contest, id=contest_id)
	return redirect("cryptics:show_contest_full", contest.id, contest.slugified)


def show_contest_full(request, contest_id, word=None):
	""" Show information about a specific contest """
	contest = get_object_or_404(
		Contest.objects.select_related("started_by", "winning_entry", "winning_entry__submitted_by"), id=contest_id
	)

	if word != contest.slugified:
		return redirect("cryptics:show_contest_full", contest.id, contest.slugified)

	contest.check_if_too_old()

	if request.method == "POST":
		if request.user.is_anonymous:
			# This is ugly but apparently the only way to get query params into the redirect
			redirect_url = reverse("account_login") + "?next=" + request.path
			return redirect(redirect_url)

		form = SubmissionForm(
			{
				"submitted_by": request.user,
				"contest": contest_id,
				"clue": request.POST.get("clue"),
				"explanation": request.POST.get("explanation"),
			}
		)

		if form.is_valid():
			form.save()
			return redirect("cryptics:show_contest", contest_id)

	else:
		form = SubmissionForm()

	context = {
		"contest": contest,
		"form": form,
		"highlight": int(request.GET.get("highlight", -1)),
	}

	return render(request, "cryptics/show.html", context)


@login_required
def delete_submission(request, submission_id):
	""" Let a user delete a clue that they submitted """
	submission = get_object_or_404(Submission, id=submission_id)
	submission.contest.check_if_too_old()

	valid = True

	if request.user != submission.submitted_by:
		messages.error(request, "You can only delete clues that you submitted")
		valid = False
	elif not submission.contest.is_submissions:
		messages.error(request, "Sorry, you can't delete a clue once voting has begun")
		valid = False

	if valid and request.method == "GET":
		if "next" in request.GET:
			next_url = request.GET["next"]
		else:
			next_url = reverse(
				"cryptics:show_contest", kwargs={"contest_id": submission.contest_id}
			)
		context = {
			"sub": submission,
			"next_url": next_url
		}
		return render(request, "cryptics/delete_clue.html", context)

	if valid and request.method == "POST":
		submission.delete()

	if "next" in request.GET:
		return redirect(request.GET["next"])

	return redirect("cryptics:show_contest", submission.contest.id)


@login_required
def add_like(request, submission_id):
	""" Let a user like a given clue """
	submission = get_object_or_404(Submission, id=submission_id)
	submission.contest.check_if_too_old()
	if not submission.contest.is_voting:
		if submission.contest.is_submissions:
			messages.error(request, "Sorry, this contest is not taking votes yet")
		else:
			messages.error(request, "Sorry, this contest has closed")
	elif request.user == submission.submitted_by:
		messages.error(request, "Sorry, you can't vote for your own submissions")
	else:
		submission.likers.add(request.user)

	if "next" in request.GET:
		return redirect(request.GET["next"])

	return redirect("cryptics:show_contest", submission.contest.id)


@login_required
def remove_like(request, submission_id):
	""" Let a user unlike a given clue """
	submission = get_object_or_404(Submission, id=submission_id)
	submission.contest.check_if_too_old()
	if submission.contest.is_voting:
		submission.likers.remove(request.user)
	else:
		if submission.contest.is_submissions:
			messages.error(request, "Sorry, this contest is not taking votes yet")
		else:
			messages.error(request, "Sorry, this contest has closed")

	if "next" in request.GET:
		return redirect(request.GET["next"])

	return redirect("cryptics:show_contest", submission.contest.id)


def all_users(request):
	""" Show the list of all users """
	return render(request, "cryptics/all_users.html", {"users": User.objects.sort_users()})


def show_user(request, user_id):
	""" Show a specific user's page """
	user = get_object_or_404(User, id=user_id)

	context = {
		"this_user": user,
		"highlight": int(request.GET.get("highlight", -1)),
		}

	return render(request, "cryptics/user_show.html", context)


def all_closed_contests(request):
	""" Show the complete list of all finished contests

	In the future, this might need to be paginated
	"""
	contests = Contest.objects.filter(status=Contest.CLOSED).order_by("created_at")
	contests = contests.select_related("started_by", "winning_entry", "winning_user")
	context = {"contests": contests}
	return render(request, "cryptics/all_closed_contests.html", context)


def contest_search_json(request):
	""" Return a list of contests matching a given string

	Currently this endpoint is only used for the "check for repeats" functionality, but could be adapted if the full
	archives page is switched to be paginated with AJAX
	"""
	search_data = ContestSearchForm(request.GET)
	if not search_data.is_valid():
		return JsonResponse({"errors": search_data.errors}, status=HTTPStatus.BAD_REQUEST)

	contests = Contest.objects.filter(word__icontains=search_data.cleaned_data["search"]).order_by("created_at")
	if (err_count := contests.count()) >= 10:
		return JsonResponse(
			{"errors": {"search": [f"Too many matching contests found ({err_count})."]}},
			status=HTTPStatus.BAD_REQUEST
		)

	contests = [{"word": contest.word, "url": contest.get_absolute_url()} for contest in contests]
	return JsonResponse({"contests": contests})

apps/cryptics/templates/cryptics/all_closed_contests.html
{% extends "./base.html" %}

{% block title %}
	Cryptic Contest -- Full Archives
{% endblock title %}

{% block content %}
	{% load static %}
	<h1>Full Archives</h1>
	<table>
		<tr>
			<th>Word</th>
			<th>Started By</th>
			<th>Started Date</th>
			<th>Winning Clue By</th>
			<th>Winning Clue</th>
			<th>Explanation (hover)</th>
		</tr>
		{% for contest in contests %}
			<tr class="{% cycle 'row1' 'row2' %}">
				<td><a href="{% url 'cryptics:show_contest_full' contest.id contest.slugified %}">{{contest.word}}</a></td>
				<td><a href="{% url 'cryptics:show_user' contest.started_by.id %}">{{ contest.started_by }}</a></td>
				<td>{{ contest.created_at }}</td>
				{% if contest.winning_entry %}
					<td><a href="{% url 'cryptics:show_user' contest.winning_user.id %}">{{ contest.winning_user }}</a></td>
					<td>{{ contest.winning_entry.clue }}</td>
					<td{% if user != sub.submitted_by %} class="explanation"{% endif %}>{{ contest.winning_entry.explanation|linebreaksbr }}</td>
				{% endif %}
			</tr>
		{% endfor %}
	</table>
	<p><a href="{% url 'cryptics:index' %}">Back</a></p>
	<script type="text/javascript" src="{% static 'cryptics/js/click_to_reveal.js' %}"></script>
{% endblock content %}

apps/cryptics/templates/cryptics/all_users.html
{% extends "./base.html" %}

{% block title %}
	Puzzlers Club Cryptic Clue Contests -- All Users
{% endblock title %}

{% block content %}
	{% load static %}
	<h1>All Users</h1>
	<table class="sortable">
		<tr>
			<th>Username</th>
			<th>Contests Won</th>
			<th>Average Likes Per Submission</th>
			<th>Total Submissions</th>
			<th>Total Likes</th>
			<th>Total Likes Given</th>
		</tr>
		{% for user_data in users %}
			<tr>
				<td><a href="{% url 'cryptics:show_user' user_data.user.id %}">{{ user_data.user.username }}</a></td>
				<td>{{ user_data.contests_won }}</td>
				<td>{{ user_data.average_likes|floatformat:-3 }}</td>
				<td>{{ user_data.total_submissions }}</td>
				<td>{{ user_data.total_likes }}</td>
				<td>{{ user_data.clues_liked }}</td>
			</tr>
		{% endfor %}
	</table>
	<p><a href="{% url 'cryptics:index' %}">Back</a></p>
	<script type="text/javascript" src="{% static 'cryptics/js/sort_table.js' %}"></script>
{% endblock content %}

apps/cryptics/templates/cryptics/base.html
<!DOCTYPE html>
<html>
	<head>
		<title>{% block title %}{% endblock title %}</title>
		<meta charset="utf-8">
		{% load static %}
		<link rel="stylesheet" type="text/css" href="{% static 'cryptics/style.css' %}">
	</head>
	<body>
		<div id="header">
			<div id="header_links">
				<a href="{% url 'cryptics:index' %}">Home</a> | <a href="{% url 'cryptics:about' %}">About</a> | <a href="{% url 'cryptics:all_users' %}">User Stats</a>
			</div>
			<div id="header_login">
				{% if user.is_authenticated %}
					Hello, <strong><a href="{% url 'cryptics:show_user' user.id %}">{{user}}</a></strong>! <a href="{% url 'account_logout' %}">Log out?</a>
				{% else %}
					<a href="{% url 'account_login' %}?next={{ request.path }}">Log in</a> to submit clues or contest words.
				{% endif %}
			</div>
		</div>
		{% if messages %}
			<ul class="messages">
				{% for message in messages %}
					<li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
				{% endfor %}
			</ul>
		{% endif %}

		{% block content %}

		{% endblock content %}
	</body>
</html>

apps/cryptics/templates/cryptics/contest_form.html
{% load static %}
{{ errors }}
{{ form.started_by.errors }}
<div{% with classes=field.css_classes %}{% if classes %} class="{{ classes }}"{% endif %}{% endwith %}>
    {{ form.word.as_field_group }}
    <br><a href="#" id="enumerate_link">Auto-enumerate</a> <a href="#" id="repeats_link">Check for repeats</a> <span id="repeats_target"></span>
</div>
<script type="text/javascript" src="{% static 'cryptics/js/enumerate.js' %}"></script>
<script type="text/javascript" src="{% static 'cryptics/js/check_for_repeats.js' %}"></script>

apps/cryptics/templates/cryptics/delete_clue.html
{% extends "./base.html" %}

{% block title %}
	Delete Clue?
{% endblock title %}

{% block content %}
	<h1>Are you sure you want to delete this clue?</h1>
	<h3>{{ sub.clue }}</h3>
	<p>{{ sub.explanation|linebreaksbr }}</p>
	<form action="{% url 'cryptics:delete_submission' sub.id %}?next={{next_url}}" method="post">
		{% csrf_token %}
		<input type="submit" value="Yes, delete this clue!">
		<a href="{{ next_url }}">No, I changed my mind.</a>
	</form>
{% endblock %}

apps/cryptics/templates/cryptics/index.html
{% extends "./base.html" %}

{% block title %}
Puzzlers Club Cryptic Clue Contests
{% endblock title %}

{% block content %}
	{% load static %}
	{% load humanize %}

	<h1>Cryptic Clue-Writing Contests</h1>

	<h3>New Contest</h3>
	<form action="" method="post">
		{% csrf_token %}
		{{ form }}
		<input type="submit" value="Create Contest">
	</form>
	<hr>
	{% if open_contests %}
		<h3>Open Contests</h3>
		<table>
			<tr>
				<th>Word</th>
				<th>Ends...</th>
				<th>Started By</th>
			</tr>
			{% for contest in open_contests %}
				<tr class="{% cycle 'row1' 'row2' %}">
					<td><a href="{% url 'cryptics:show_contest_full' contest.id contest.slugified %}">{{contest.word}}</a></td>
					<td>{{contest.submissions_end_time|naturaltime}}</td>
					<td><a href="{% url 'cryptics:show_user' contest.started_by.id %}">{{contest.started_by}}</a></td>
				</tr>
			{% endfor %}
		</table>
	{% else %}
		<p>No open contests currently. {% if user.is_authenticated %}Start one!{% endif %}</p>
	{% endif %}
	{% if voting_contests %}
		<hr>
		<h3>Vote For Your Favorite Clue Now!</h3>
		<table>
			<tr>
				<th>Word</th>
				<th>Voting Ends...</th>
			</tr>
			{% for contest in voting_contests %}
				<tr class="{% cycle 'row1' 'row2' %}">
					<td><a href="{% url 'cryptics:show_contest_full' contest.id contest.slugified %}">{{contest.word}}</a></td>
					<td>{{contest.voting_end_time|naturaltime}}</td>
				</tr>
			{% endfor %}
		</table>
	{% endif %}
	<hr>
	<p><strong>The current champion is {{ current_champ.user }}, with {{ current_champ.contests_won }} win{{ current_champ.contests_won|pluralize }}!  All hail {{ current_champ.user }}!</strong>  <a href="{% url 'cryptics:all_users' %}">Full stats</a></p>
	{% if recent_clues %}
		<hr>
		<h3>Recent Clues</h3>
		<table>
			<tr>
				<th>Contest</th>
				<th>Clue</th>
				<th>Explanation (hover)</th>
				<th>Submitted</th>
			</tr>
			{% for sub in recent_clues %}
				<tr class="{% cycle 'row1' 'row2' %}">
					<td><a href="{% url 'cryptics:show_contest_full' sub.contest.id sub.contest.slugified %}?highlight={{sub.id}}#clue{{sub.id}}">{{sub.contest.word}}</td>
					<td>{{sub.clue}}</td>
					<td{% if user != sub.submitted_by %} class="explanation"{% endif %}>{{sub.explanation|linebreaksbr}}</td>
					<td>{{sub.created_at|naturaltime}}</td>
					{% if user.is_authenticated and user != sub.submitted_by and not sub.contest.is_submissions %}
						<td>
							{% if user in sub.likers.all %}
								{% if sub.contest.is_voting %}
									<a href="{% url 'cryptics:remove_like' sub.id %}?next={% url 'cryptics:index' %}"><img src="{% static 'cryptics/images/filled_star.png' %}" title="Un-like this clue?" alt="filled star" class="like_star"></a>
								{% else %}
									<img src="{% static 'cryptics/images/filled_star.png' %}" title="You liked this clue" alt="filled star" class="like_star">
								{% endif %}
							{% else %}
								{% if sub.contest.is_voting %}
									<a href="{% url 'cryptics:add_like' sub.id %}?next={% url 'cryptics:index' %}"><img src="{% static 'cryptics/images/empty_star.png' %}" title="Like this clue?" alt="empty star" class="like_star"></a>
								{% else %}
									<img src="{% static 'cryptics/images/empty_star.png' %}" title="You didn't like this clue" alt="empty star" class="like_star">
								{% endif %}
							{% endif %}
						</td>
					{% endif %}
					{% if sub.contest.is_submissions and user == sub.submitted_by %}
						<td><a href="{% url 'cryptics:delete_submission' sub.id %}?next={% url 'cryptics:index' %}"><img src="{% static 'cryptics/images/delete_button.png' %}" title="Delete this clue?" alt="delete" class="like_star"></a></td>
					{% endif %}
				</tr>
			{% endfor %}
		</table>
	{% endif %}

	{% if past_contests %}
		<hr>
		<h3>Past Contests</h3>
		<table>
			<tr>
				<th>Contest</th>
				<th>Winning Clue</th>
				<th>Explanation (hover)</th>
				<th>Submitted By</th>
			</tr>
			{% for contest in past_contests %}
				<tr class="{% cycle 'row1' 'row2' %}">
					<td><a href="{% url 'cryptics:show_contest_full' contest.id contest.slugified %}">{{ contest.word }}</a> (ended {{ contest.voting_end_time|timesince }} ago)</td>
					<td>{{ contest.winning_entry.clue }}</td>
					<td{% if user != sub.submitted_by %} class="explanation"{% endif %}>{{ contest.winning_entry.explanation|linebreaksbr }}</td>
					<td>{{ contest.winning_entry.submitted_by }}</td>
				</tr>
			{% endfor %}
		</table>
		...
	{% endif %}
	<p><a href="{% url 'cryptics:all_closed_contests' %}">Full Archives</a></p>

	<script type="text/javascript" src="{% static 'cryptics/js/click_to_reveal.js' %}"></script>
{% endblock content %}

apps/cryptics/templates/cryptics/show.html
{% extends "./base.html" %}

{% block title %}
	Cryptic Contest: {{ contest.word }}
{% endblock title %}

{% block content %}
	{% load static %}

	<h1>{{contest.word}}</h1>
	<p><em>Started by <a href="{% url 'cryptics:show_user' contest.started_by.id %}">{{contest.started_by}}</a></em></p>
	{% if contest.is_submissions %}
		<form action="" method="post">
			{% csrf_token %}
			{{ form }}
			<input type="submit" value="Submit">
		</form>
	{% endif %}
	{% if contest.winning_entry %}
		<div class="winner_box">
			<p class="winner">{{ contest.winning_entry.clue }}</p>
			<p>{{ contest.winning_entry.explanation|linebreaksbr }}</p>
			<p>Submitted by {{ contest.winning_entry.submitted_by }}</p>
		</div>
	{% endif %}
	<h3>All Submissions</h3>
	{% if contest.submissions.exists %}
		<table>
			<tr>
				<th>Clue ID</th>
				<th>Clue</th>
				<th>Explanation (hover)</th>
				{% if contest.is_closed %}
					<th>Submitted By</th>
					<th>Likes</th>
				{% endif %}
			</tr>
			{% for sub in contest.submissions_sorted %}
				{% if sub.id == highlight %}
					<meta name="twitter:card" content="summary" />
					<meta name="twitter:title" content="{{sub.clue}}" />
				{% endif %}
				<tr class="{% cycle 'row1' 'row2' %}"{% if sub.id == highlight %} id="highlight"{% endif %}>
					<td><a name="clue{{ sub.id }}" href="{{sub.get_absolute_url}}">{{sub.id}}</td>
					<td>{{sub.clue}}</td>
					<td{% if user != sub.submitted_by %} class="explanation"{% endif %}>{{sub.explanation|linebreaksbr}}</td>
					{% if contest.is_closed %}
						<td><a href="{% url 'cryptics:show_user' sub.submitted_by.id %}">{{sub.submitted_by}}</a></td>
						<td title="{{sub.likers.all|join:', '}}">{{sub.likers.count}}</td>
					{% endif %}
					{% if not contest.is_submissions %}
						{% if user.is_authenticated and user != sub.submitted_by %}
							<td>
								{% if user in sub.likers.all %}
									{% if contest.is_voting %}
										<a href="{% url 'cryptics:remove_like' sub.id %}?next={% url 'cryptics:show_contest' contest.id %}"><img src="{% static 'cryptics/images/filled_star.png' %}" title="Un-like this clue?" alt="filled star" class="like_star"></a>
									{% else %}
										<img src="{% static 'cryptics/images/filled_star.png' %}" title="You liked this clue" alt="filled star" class="like_star">
									{% endif %}
								{% else %}
									{% if contest.is_voting %}
										<a href="{% url 'cryptics:add_like' sub.id %}?next={% url 'cryptics:show_contest' contest.id %}"><img src="{% static 'cryptics/images/empty_star.png' %}" title="Like this clue?" alt="empty star" class="like_star"></a>
									{% else %}
										<img src="{% static 'cryptics/images/empty_star.png' %}" title="You didn't like this clue" alt="empty star" class="like_star">
									{% endif %}
								{% endif %}
							{% endif %}
						</td>
					{% else %}
						{% if user == sub.submitted_by %}
							<td><a href="{% url 'cryptics:delete_submission' sub.id %}?next={% url 'cryptics:show_contest' contest.id %}"><img src="{% static 'cryptics/images/delete_button.png' %}" title="Delete this clue?" alt="delete" class="like_star"></a></td>
						{% endif %}
					{% endif %}
				</tr>
			{% endfor %}
		</table>
	{% else %}
		<p>Sorry, none yet. {% if contest.is_submissions %}Be the first!{% endif %} </p>
	{% endif %}
	<a href="{% url 'cryptics:index' %}">Back</a>

	<script type="text/javascript" src="{% static 'cryptics/js/click_to_reveal.js' %}"></script>
	<script type="text/javascript" src="{% static 'cryptics/js/warn_about_enumeration.js' %}"></script>
{% endblock content %}

apps/cryptics/templates/cryptics/user_show.html
{% extends "./base.html" %}

{% block title %}
	{{ this_user.username }}
{% endblock title %}

{% block content %}
	{% load static %}
	<h1>{{ this_user.username }}</h1>
	<p><strong>Contests started:</strong>
		{% for contest in this_user.contests_started.all %}
			<a href="{% url 'cryptics:show_contest_full' contest.id contest.slugified %}">{{ contest.word }}</a>{% if not forloop.last %}, {% endif %}
		{% empty %}
			None!
		{% endfor %}
	</p>
	<p><strong>Contests won:</strong>
		{% for contest in this_user.contests_won.all %}
			<a href="{% url 'cryptics:show_contest_full' contest.id contest.slugified %}">{{ contest.word }}</a>{% if not forloop.last %}, {% endif %}
		{% empty %}
			None!
		{% endfor %}
	</p>
	<h3>All Submissions</h3>
	{% if this_user.submissions.exists %}
		<table>
			<tr>
				<th>Clue ID</th>
				<th>Contest</th>
				<th>Clue</th>
				<th>Explanation (hover)</th>
				<th>Submitted By</th>
				<th>Likes</th>
			</tr>
			{% comment %}
				Note that this needs to be this_user.submissions.all.order_by_like_count, not just
				this_user.submissions.order_by_like_count.  order_by_like_count is a method of the SubmissionQuerySet;
				this_user.submissions alone will return a related manager, and so adding .all is required to get a
				queryset.
			{% endcomment %}
			{% for sub in this_user.submissions.all.order_by_like_count %}
				{% if sub.contest.is_closed or user == this_user %}
					{% if sub.id == highlight %}
						<meta name="twitter:card" content="summary" />
						<meta name="twitter:title" content="{{sub.clue}}" />
					{% endif %}
					<tr class="{% cycle 'row1' 'row2' %}"{% if sub.id == highlight %} id="highlight"{% endif %}>
						<td><a name="clue{{ sub.id }}" href="{% url 'cryptics:show_user' this_user.id %}?highlight={{sub.id}}#clue{{sub.id}}">{{sub.id}}</td>
						<td><a href="{% url 'cryptics:show_contest_full' sub.contest.id sub.contest.slugified %}">{{sub.contest.word}}</a></td>
						<td>{{sub.clue}}</td>
						<td{% if user != this_user %} class="explanation"{% endif %}>{{sub.explanation|linebreaksbr}}</td>
						<td>{{sub.submitted_by}}</td>
						<td title="{{sub.likers.all|join:', '}}">
							{% if not sub.contest.is_submissions %}
								{{sub.like_count}}
							{% else %}
								Still open
							{% endif %}
						</td>
						{% if user.is_authenticated and user != this_user %}
							<td>
								{% if not sub.contest.is_submissions %}
									{% if user in sub.likers.all %}
										<img src="{% static 'cryptics/images/filled_star.png' %}" title="You liked this clue" alt="filled star" class="like_star">
									{% else %}
										<img src="{% static 'cryptics/images/empty_star.png' %}" title="You didn't like this clue" alt="empty star" class="like_star">
									{% endif %}
								{% endif %}
							</td>
						{% endif %}
						{% if user == this_user and sub.contest.is_submissions %}
							<td><a href="{% url 'cryptics:delete_submission' sub.id %}?next={% url 'cryptics:show_user' this_user.id %}"><img src="{% static 'cryptics/images/delete_button.png' %}" title="Delete this clue?" alt="delete" class="like_star"></a></td>
						{% endif %}
					</tr>
				{% endif %}
			{% endfor %}
		</table>
	{% else %}
		<p>None!</p>
	{% endif %}
	<p><a href="{% url 'cryptics:all_users' %}">Back to stats</a></p>
	<p><a href="{% url 'cryptics:index' %}">Back to main</a></p>

	<script type="text/javascript" src="{% static 'cryptics/js/click_to_reveal.js' %}"></script>
{% endblock content %}